package model;

public class Battery extends Pieces {
    private String type;
    private double capacity;
    private boolean autoGenerated;

    public Battery(String named, double price, String type, double capacity, boolean autoGenerated) {
        super(named, price);
        this.type = type;
        this.capacity = capacity;
        this.autoGenerated = autoGenerated;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public double getCapacity() {
        return capacity;
    }

    public void setCapacity(double capacity) {
        this.capacity = capacity;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    @Override
    public double priceWithProcents() {
        return getPrice()+20;
    }

    @Override
    public double getPrice() {
        return super.getPrice();
    }

    @Override
    public String toString() {
        return "Battery{" +
                "type='" + type + '\'' +
                ", capacity=" + capacity +
                ", autoGenerated=" + autoGenerated +
                '}';
    }
}
