package model.baterry_company;

import model.Battery;

public class UltraEnergy extends Battery {
    private double priceInEuro;
    private boolean safeUsage;

    public UltraEnergy(String named, double price, String type, double capacity, boolean autoGenerated, double priceInEuro, boolean safeUsage) {
        super(named, price, type, capacity, autoGenerated);
        this.priceInEuro = priceInEuro;
        this.safeUsage = safeUsage;
    }

    @Override
    public String toString() {
        return "UltraEnergy{" +
                "priceInEuro=" + priceInEuro +
                ", safeUsage=" + safeUsage +
                '}';
    }

    public double getPriceInEuro() {
        return priceInEuro;
    }

    public void setPriceInEuro(double priceInEuro) {
        this.priceInEuro = priceInEuro;
    }

    public boolean isSafeUsage() {
        return safeUsage;
    }

    public void setSafeUsage(boolean safeUsage) {
        this.safeUsage = safeUsage;
    }
}
